// MITRE ATT&CK® Enterprise lookup (pure): technique names, tactics and a matrix view of observed
// techniques. Data: src/core/attack-data.json, generated by scripts/make-attack-data.mjs from MITRE's
// official STIX bundle. © The MITRE Corporation — reproduced with permission (engines/licenses/mitre-attack.txt).

import data from './attack-data.json';

interface AttackData {
  version: string | null;
  source: string;
  tactics: Array<{ id: string; short: string; name: string }>;
  techniques: Record<string, [string, string[]]>;
  /** Revoked id → the id that replaced it (MITRE "revoked-by"). */
  revoked: Record<string, string>;
}
const D = data as unknown as AttackData;

export const ATTACK_VERSION = D.version;
export const ATTACK_TACTICS = D.tactics;

export interface TechniqueInfo {
  id: string;
  name: string;
  /** For a sub-technique, the parent's name ("Process Injection"). */
  parentName: string | null;
  /** The older id this was looked up by, when MITRE has since replaced it. */
  replaces: string | null;
  tactics: string[];
  url: string;
}

export function technique(rawId: string): TechniqueInfo | null {
  const asked = rawId.trim().toUpperCase();
  if (!/^T\d{4}(\.\d{3})?$/.test(asked)) return null;
  const id = D.techniques[asked] ? asked : D.revoked[asked] ?? asked;
  const hit = D.techniques[id];
  if (!hit) return null;
  const parent = id.includes('.') ? D.techniques[id.split('.')[0]!] : undefined;
  return { id, name: hit[0], parentName: parent?.[0] ?? null, replaces: id === asked ? null : asked, tactics: hit[1], url: `https://attack.mitre.org/techniques/${id.replace('.', '/')}/` };
}

export interface MatrixColumn {
  tactic: { id: string; short: string; name: string };
  techniques: Array<TechniqueInfo & { count: number }>;
}

/** Observed techniques arranged by tactic in kill-chain order (a technique can sit under several tactics). */
export function attackMatrix(observed: Array<{ id: string; count: number }>): MatrixColumn[] {
  const cols = new Map(D.tactics.map((t) => [t.short, { tactic: t, techniques: [] as MatrixColumn['techniques'] }]));
  const seen = new Map<string, number>();
  for (const o of observed) {
    const id = o.id.trim().toUpperCase();
    seen.set(id, (seen.get(id) ?? 0) + o.count);
  }
  const merged = new Map<string, TechniqueInfo & { count: number }>();
  for (const [id, count] of seen) {
    const t = technique(id);
    if (!t) continue;
    const prev = merged.get(t.id);
    merged.set(t.id, prev ? { ...prev, count: prev.count + count } : { ...t, count });
  }
  for (const t of merged.values()) for (const tac of t.tactics) cols.get(tac)?.techniques.push(t);
  return [...cols.values()].filter((c) => c.techniques.length > 0).map((c) => ({ ...c, techniques: c.techniques.sort((a, b) => b.count - a.count || a.id.localeCompare(b.id)) }));
}
