// Offline MAC address → manufacturer lookup (pure). Data: src/core/oui-data.json, generated by
// scripts/make-oui-data.mjs from the IEEE MA-L registry (via the BSD-2 `oui-data` package).
//
// Deliberately local: looking a MAC prefix up online would send the addresses of the user's devices
// to a third party. Unknown prefixes return null, never a guess.

import data from './oui-data.json';

export const OUI_SOURCE: string = (data as { source: string }).source;

let table: Map<string, string> | null = null;
function load(): Map<string, string> {
  if (table) return table;
  const d = data as { names: string[]; table: string };
  table = new Map();
  for (const row of d.table.split(',')) {
    const name = d.names[parseInt(row.slice(6), 36)];
    if (name) table.set(row.slice(0, 6), name);
  }
  return table;
}

/** Canonical "AA:BB:CC:DD:EE:FF", or null when the value isn't a MAC address. */
export function normalizeMac(mac: string | null | undefined): string | null {
  if (!mac) return null;
  const hex = mac.replace(/[^0-9a-fA-F]/g, '');
  if (hex.length !== 12) return null;
  return hex.toUpperCase().match(/.{2}/g)!.join(':');
}

export type MacKind = 'vendor' | 'random' | 'multicast' | 'broadcast' | 'unknown';

export interface MacInfo {
  mac: string;
  kind: MacKind;
  /** Manufacturer from the IEEE registry, when the prefix is registered. */
  vendor: string | null;
}

/**
 * Describes a MAC address. A locally administered address (second hex digit 2, 6, A or E) is not
 * tied to a manufacturer: phones and laptops use such random addresses for privacy on Wi-Fi.
 */
export function macInfo(raw: string | null | undefined): MacInfo | null {
  const mac = normalizeMac(raw);
  if (!mac) return null;
  if (mac === 'FF:FF:FF:FF:FF:FF') return { mac, kind: 'broadcast', vendor: null };
  const first = parseInt(mac.slice(0, 2), 16);
  if (first & 0x01) return { mac, kind: 'multicast', vendor: null };
  if (first & 0x02) return { mac, kind: 'random', vendor: null };
  const vendor = load().get(mac.slice(0, 8).replace(/:/g, '')) ?? null;
  return { mac, kind: vendor ? 'vendor' : 'unknown', vendor };
}
